# Generated by Django 5.2 on 2025-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='other_images',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.ManyToManyField(related_name='service_sub_categories', to='categories.category'),
        ),
    ]
