# Generated by Django 5.2 on 2025-04-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='main_category',
            new_name='children',
        ),
    ]
