# Generated by Django 5.2 on 2025-04-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_name_category_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='children',
            new_name='parent',
        ),
    ]
