# Generated by Django 5.2 on 2025-04-30 01:15

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='parent', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.category'),
        ),
    ]
